title: We CodeSign Podcast
email: wecodesignpodcast@gmail.com
description: "El podcast de diseño y desarrollo web"
baseurl: ""
url: "http://wecodesignpodcast.com"
twitter_username: WeCodeSignPD

# Build settings
markdown: kramdown
paginate_path: /blog/page:num
paginate: 10
permalink: pretty
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate